#==================================
FROM mariadb:lts AS mysql
#==================================

ENV MYSQL_ALLOW_EMPTY_PASSWORD=yes
#==============================
FROM mysql AS mysql-defaultargs
#==============================
